version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.10.6
    working_directory: ~/udacity-capstone
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run:
          name: install dependencies and lint
          command: |
            curl -L "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64" -o /usr/local/bin/hadolint && chmod +x /usr/local/bin/hadolint
            python3 -m venv ~/.venv-capstone && source ~/.venv-capstone/bin/activate && pip3 install -r requirements.txt
            pylint app.py --disable=C0111,C0114,C0116
            flake8 app.py
            hadolint Dockerfile
      - save_cache:
          paths:
            - ~/.venv-capstone
          key: dependencies

workflows:
  default:
    jobs:
      - lint