---
- name: "Download AWS CLI"
  shell: sudo rm -rf aws* && wget -O aws.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" && unzip aws.zip
  become: yes

- name: "Install the AWS CLI"
  shell: sudo aws/install --update
  become: yes
  