---
- name: "Install needed dependencies"
  hosts: management
  user: ubuntu
  gather_facts: false
  become: yes
  pre_tasks:
    - name: "Install 'unzip'"
      become: yes
      apt:
        name: [ "unzip" ]
        state: latest
        update_cache: yes

  roles:
    - install-awscli
    - install-kubectl

- name: "Configure AWS credentials"
  hosts: management
  user: ubuntu
  gather_facts: false
  tasks:
    - name: Ensure AWS directory exists
      file:
        path: ~/.aws
        recurse: yes
        state: directory
    - name: Copy creds
      copy:
        src: credentials
        dest: ~/.aws/credentials
    - name: Copy config
      copy:
        src: config
        dest: ~/.aws/config

- name: "Fetch kubectl config"
  hosts: management
  user: ubuntu
  gather_facts: false
  vars:
  pre_tasks:
    - name: Create a kubeconfig file for the cluster
      shell: "aws eks update-kubeconfig --region us-east-1 --name cluster"
