---
- name: "Install needed dependencies"
  hosts: management
  user: ubuntu
  gather_facts: false
  become: yes
  pre_tasks:
    - name: "Install 'unzip'"
      become: yes
      apt:
        name: [ "unzip" ]
        state: latest
        update_cache: yes

  roles:
    - install-awscli
    - install-kubectl

- name: "Configure AWS credentials"
  hosts: management
  user: ubuntu
  gather_facts: false
  tasks:
    copy:
      src: "credentials"
      dest: ~/.aws/credentials
    copy:
      src: "config"
      dest: ~/.aws/config

- name: "Fetch kubectl config"
  hosts: management
  user: ubuntu
  gather_facts: false
  vars:
  pre_tasks:
    - name: Create a kubeconfig file for the cluster
      shell: "aws eks update-kubeconfig --region us-east-1 --name cluster"
